config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  root 'posts#index'

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :update, :destroy, :edit]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show

  end

  def edit;end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_comment">
    <p class="comment_name">
      <b><em><%= comment.name %></em></b>
    </p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_title"><%= time_ago_in_words(comment.created_at) %></p>
    <% if user_signed_in? %>
      <p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: 'button', data: { confirm: "Are you sure?" } %></p>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do | f | %>
  <p>
    <%= f.label :name %></br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %></br>
    <%= f.text_area :body %>
  </p>
  </br>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblr</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', "https://fonts.googleapis.com/css?family=Raleway:400,700" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="sidebar">
      <ul>
        <li class="category"><%= link_to "Tumblr", root_path %></li>
        <li><%= link_to "Posts", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      <p class="sign_in">
        <% unless user_signed_in? %>
          <%= link_to "User Login", new_user_session_path %>
        <% end %>
      </p>
    </div>

    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>Post Feed</p>
        <% elsif current_page?(about_path) %>
          <p>My site</p>
        <% else %>
          <%= link_to "Back to Post Feed", root_path %>
        <% end %>

        <% if user_signed_in? %>
          <div class="buttons">
            <%= link_to "Make Post", new_post_path, class: 'button' %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'button' %>
          </div>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
      <% end %>

      <%= yield %>

    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "profile.jpeg" %>
  </div>

  <div id="content">
    <h1>It's Mr. Stick Figure</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %></h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do | post | %>
<div class="post_wrapper">
  <h2 class="title"><%= link_to post.title, post %></h2>
  <p class="body"><%= truncate(post.body, length: 50) %></p>
  <p class="date"><%= time_ago_in_words(post.created_at) %></p>
</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>Create Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title"><%= @post.title %></h1>

  <p class="date">
    <%= time_ago_in_words(@post.created_at) %>|
    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_post_path(@post) %>|
      <%= link_to 'Delete', post_path(@post), method: :delete %>
    <% end %>
  </p>
  <p class="body"><%= @post.body %></p>
  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
    <h2>Join Discussion:</h2>
    <%= render "comments/form"%>
  </div>
</div>